# Generated by Django 4.2.2 on 2023-07-03 18:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=250, null=True)),
                ("subtitle", models.CharField(blank=True, max_length=250, null=True)),
                ("meta_title", models.CharField(blank=True, max_length=250, null=True)),
                ("meta_description", models.CharField(blank=True, max_length=250, null=True)),
                ("description", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "long_description",
                    ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=250, null=True),
                ),
            ],
        ),
    ]
